version: '3.8'
services:
  test-postgres-db:
    container_name: test-postgres-db
    restart: always
    image: postgres:15.6-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
