apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: notes-backend
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: notes-backend/user-service:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: notes-config
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: '300Mi'
              cpu: '200m'
            limits:
              memory: '400Mi'
