apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: {{.Release.Namespace}}
  labels:
    app: gateway-service
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: '{{.Values.deployment.image.repository}}:{{.Values.deployment.image.tag}}'
          imagePullPolicy: {{.Values.deployment.imagePullPolicy}}
          envFrom:
            - configMapRef:
                name: notes-config
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '300Mi'
              cpu: '200m'
            limits:
              memory: '400Mi'
