services:
  postgres-db:
    container_name: postgres-db
    restart: always
    image: postgres:15.6-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      # postgres doesn't create DB automatically. Find a way to create DB automatically on init
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${DB_NAME} -U ${DB_USER}']
      interval: 10s
      timeout: 2s
      retries: 10

volumes:
  pgdata:
    name: postgres_delivery
    driver: local
