version: '3.8'
services:
  loki:
    image: grafana/loki:2.9.10
    command: -config.file=/etc/loki/loki-config.yml
    restart: unless-stopped
    volumes:
      - ../config/loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - loki
    ports:
      - '3100:3100'

  promtail:
    image: grafana/promtail:2.9.10
    volumes:
      - ../config/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # https://ruanbekker.medium.com/logging-with-docker-promtail-and-grafana-loki-d920fd790ca8
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.0.0
    user: '501'
    restart: unless-stopped
    volumes:
      - ../config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ../grafana:/var/lib/grafana
    ports:
      - '9000:3000'
    networks:
      - loki

networks:
  loki:
