name: E2E Tests Workflow

on:
  workflow_call:

jobs:
  run-e2e-test:
    name: Run e2e Test
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:15.6-alpine
    #     env:
    #       POSTGRES_PASSWORD: root
    #       POSTGRES_USER: root
    #       POSTGRES_DB: test_delivery_db
    #     ports:
    #       - 5444:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Set Environment Variables
        run: cp ./apps/supplier-service/.env.test ./packages/common/.env

      - name: Install Docker using Docker's official script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
        continue-on-error: false

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
        continue-on-error: false

      # - name: Run docker-compose
      #   uses: hoverkraft-tech/compose-action@v2.0.1
      #   with:
      #     up-flags: '--env-file ./apps/supplier-service/.env.test'
      #     compose-file: './apps/supplier-service/docker-compose.test.yaml'

      - name: Run e2e Test
        run: pnpm test:e2e
