name: Verify Workflow

on:
  workflow_call:
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  run-lint:
    uses: ./.github/workflows/lint.yaml

  run-unit-tests:
    uses: ./.github/workflows/test.yaml

  run-e2e-tests:
    needs: [run-unit-tests, run-lint]
    uses: ./.github/workflows/test:e2e.yaml
